"""Add report_path to UploadedModel

Revision ID: 824f19af5f7c
Revises: e129d3cfba14
Create Date: 2025-07-09 16:08:41.616087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824f19af5f7c'
down_revision = 'e129d3cfba14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_model', schema=None) as batch_op:
        batch_op.drop_column('report_path')

    # ### end Alembic commands ###
